download_images:
	# Link to /Nextcloud/Shared/2020-02-01 RMURV2/2020-02-14PumpkinImagesForMiniproject.zip
	wget https://nextcloud.sdu.dk/index.php/s/eHoWBJETgkcWNzy/download
	unzip download
	rm download
